name: minecheck
on: [push, pull_request]
jobs:
  minecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Luacheck
      uses: S-S-X/minecheck@master
      with:
        args: mods